Dev giogio
fchinu/Limadou-Event-Display pull request #10
Opened 2024-03-22 07:40 UTC by GiorgioAlbertoLucia

fileManager added to read data from file. Clusterer is now updated and performs the entire clustering algorithm. A new constructor is required in Cluster.h

2024-03-23 09:25 UTC, fchinu requested changes
Hello @GiorgioAlbertoLucia! I have finished reviewing your PR, which looks good to me. I only have this minor comment, then we are ready to start clustering! Please make sure to fix your branch history, since this PR also contains older commits (already merged), making it difficult to review

2024-03-23 09:25 UTC, fchinu commented on Clustering/src/clusterer.cxx
> +          if (std::abs(x[index] - x[j]) == 1 + std::abs(y[index] - y[j]) <= 1)
```suggestion
          if (std::abs(x[index] - x[j]) + std::abs(y[index] - y[j]) <= 1)
```

2024-03-24 17:25 UTC, fchinu commented
Many thanks @GiorgioAlbertoLucia! PR #7 added the requirement for clang-formatting, can you run `clang-format -i fileneme` to the files that do not pass this check? Also I see that I cannot merge because `This branch is out-of-date with the base branch
`, I guess you can click on `update branch` in your branch? I think I can do it, but don't want to risk to ruin your work

2024-03-24 18:48 UTC, GiorgioAlbertoLucia commented
Done

2024-03-24 18:51 UTC, fchinu approved these changes
Thank you!

2024-03-24 18:51 UTC, merged