Detector display added
fchinu/Limadou-Event-Display pull request #16
Opened 2024-03-30 10:22 UTC by GiorgioAlbertoLucia

Detector display was added. A nice png is also included. Everything works in ROOT 
$ root -l
$ .x LoadMacros.cpp
$ .x Display.cpp

The python wrapping (Display.py) does not work, due to issues in passing a 2d array as an argument (again, this works in c++). Some help would be appreciated

2024-03-30 12:50 UTC, Roberta-Ferioli approved these changes
Thank you @GiorgioAlbertoLucia for this impressive work. For me it is ok. If you want you can merge it

2024-03-30 16:04 UTC, fchinu requested changes
Hi @GiorgioAlbertoLucia, thanks a lot for the many additions! We discussed a bit offline how to handle the python script; I have few comments on top of it

2024-03-30 16:04 UTC, fchinu commented on Event_Display/scripts/Display.py
> +ROOT.gInterpreter.ProcessLine('#include "../src/DetectorModule.cxx"')
We can run the script from base directory this way
```suggestion
ROOT.gInterpreter.ProcessLine('#include "Event_Display/src/DetectorChip.cxx"') 
ROOT.gInterpreter.ProcessLine('#include "Event_Display/src/DetectorModule.cxx"')
```

2024-03-30 16:04 UTC, fchinu commented on Event_Display/scripts/LoadMacros.cpp
> +  gSystem->CompileMacro("../src/Detector.cxx", "kg", "", "../build");
Check this also for the header files, please
```suggestion
  gSystem->CompileMacro("Event_Display/src/DetectorChip.cxx", "kg", "", "../build");
  gSystem->CompileMacro("Event_Display/src/DetectorModule.cxx", "kg", "", "../build");
  gSystem->CompileMacro("Event_Display/src/Detector.cxx", "kg", "", "../build");
```

2024-03-30 16:04 UTC, fchinu commented on Event_Display/src/DetectorModule.cxx
> +                               unsigned (&chipIDs)[chipsY][chipsX])
I would use the standard (x,y) notation here, to avoid confusion
```suggestion
                               unsigned (&chipIDs)[chipsX][chipsY])
```

2024-03-30 16:04 UTC, fchinu commented on Event_Display/src/DetectorModule.cxx
> +  }
```suggestion
  fChipIDs = new unsigned *[fNChipsX];
  for (unsigned ix = 0; ix < fNChipsX; ix++) {
    fChipIDs[ix] = new unsigned[fNChipsX];
    for (unsigned iy = 0; iy < fNChipsY; iy++) {
      fChipIDs[ix][iy] = chipIDs[ix][iy];
    }
  }
```

2024-03-30 16:04 UTC, fchinu commented on Event_Display/src/DetectorModule.cxx
> +  }
```suggestion
  for (unsigned ix = 0; ix < fNChipsX; ix++) {
    delete[] fChipIDs[ix];
  }
```

2024-03-30 16:04 UTC, fchinu commented on Event_Display/src/DetectorModule.h
> +                 const DetectorChip &chip, unsigned (&chipIDs)[chipsY][chipsX]);
```suggestion
                 const DetectorChip &chip, unsigned (&chipIDs)[chipsX][chipsY]);
```

2024-03-31 20:59 UTC, GiorgioAlbertoLucia commented
Changes to the x, y indices implemented. 
Display.py now works

2024-04-01 08:21 UTC, Roberta-Ferioli commented on Event_Display/DetectorDisplay.png
Just a dummy question. Why are the modules vertical? The surface should be upwards

2024-04-05 17:18 UTC, fchinu approved these changes

2024-04-08 20:52 UTC, merged