Dev giogio
fchinu/Limadou-Event-Display pull request #5
Opened 2024-03-19 14:43 UTC by GiorgioAlbertoLucia

Branch with clustering algorithm added

2024-03-19 14:47 UTC, Roberta-Ferioli approved these changes

2024-03-19 14:52 UTC, fchinu requested changes
Thanks @GiorgioAlbertoLucia ! I will check the rest of the code by this evening, I promise

2024-03-19 14:52 UTC, fchinu commented on .vscode/settings.json
Could you please add .vscode to .gitinclude?

2024-03-20 15:21 UTC, fchinu requested changes
Thanks a lot @GiorgioAlbertoLucia! Last thing and I approve: can you remove .vscode from the repo?

2024-03-21 16:21 UTC, GiorgioAlbertoLucia commented
Done

2024-03-21 16:33 UTC, fchinu approved these changes
Thanks a lot!

2024-03-21 16:34 UTC, merged